export const CART_ADD_ITEM = 'ADD_TO_CART';
export const CART_REMOVE_ITEM = 'REMOVE_FROM_CART';

export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';
